# Generated by Django 4.1.6 on 2023-02-28 07:21

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_pic/default/default.avif', upload_to=users.models.image_path, verbose_name='Profile Photos'),
        ),
    ]
