# Generated by Django 4.1.6 on 2023-02-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_pic/default/default.avif', upload_to='', verbose_name='Profile Photo'),
        ),
    ]
