# Generated by Django 4.1.6 on 2023-02-28 07:35

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_pic/default/default.avif', upload_to=api.models.image_path, verbose_name='Profile Photo'),
        ),
    ]
