# Generated by Django 4.1.6 on 2023-03-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='About_Me',
            field=models.TextField(blank=True, max_length=700, null=True, verbose_name='About Me'),
        ),
    ]
